### ISSUE TITLE
Sugestia dotycząca pytania kat. A, dział 1, nr 71

### ISSUE THREAD

**Issue by SP5D** [HackerspaceKRK/pytania-egzaminacyjne#111]
**Aktualna treść pytania:** Żarówka 12 V pobiera z baterii 0,1 A. Jaką oporność ma żarówka?

**Odpowiedzi:** oporność 120 Ω, oporność 12 Ω, oporność 1,2 Ω

---

Treść uwagi: 

Błędnie przepisana odpowiedź C.

Jest | Powinno być
--- | ---
oporność 1,2 Ω | oporność 1,2 kΩ 

Oryginalny materiał porównawczy:
strona 2/62
https://bip.uke.gov.pl/download/gfx/bip/pl/defaultaktualnosci/130/3/302/material_pomocniczy_test_klasa_a.pdf

_(Błąd to błąd. Co z tego, że bez znaczenia? ;) )_

**Comment by wprzyb** [comment]
Jak już wspomniałeś, bez znaczenia.
