### ISSUE TITLE
Zbudować jakieś rozwiązanie naokoło buga w githubie przy zgłaszaniu z linku

### ISSUE THREAD

**Issue by wprzyb** [HackerspaceKRK/pytania-egzaminacyjne#45]
Bug, który w #26 i #27 spowodował skopiowanie treści poprzedniego tworzonego issue pasuje jakoś zakomunikować zgłaszającym tak, żeby byli tego świadomi i nie powstawały duplikaty.

Bug polega na tym, że po otwarciu zgłoszenia przez przycisk i cofnięciu się do listy pytań i zgłoszeniu kolejnej uwagi, github nie wiedzieć czemu kopiuje treść poprzednio stworzonego zgłoszenia

**Comment by wprzyb** [comment]
Pomysł 1) Można dopisać w treści templatki 
> uwaga, sprawdź treść zgłoszenia przed wysłaniem, github lubi psocić

**Comment by Sebart** [comment]
pomaga ponowne otwarcie linku do pytań w nowym oknie i komentowanie tylko jednego pytania w ramach takiej 'sesji'

**Comment by wprzyb** [comment]
Jak problem dalej będzie, to się issue z powrotem dźwignie
