### ISSUE TITLE
Sugestia zbiorowa

### ISSUE THREAD

**Issue by olgierd** [HackerspaceKRK/pytania-egzaminacyjne#6]
Świetne pytania! Zanotowałem kilka rzeczy co do których mam wątpliwości

#6 - odpowiedź "A" - w sumie jest sensowna
#14 - "by ograniczyć prąd" - to wystarczy dowolny, ale chcemy ograniczyć go do w/w wartości :-)
#19 - w sumie dość trudne pytanie - żaden odbiornik (fabryczny) nie ma chyba możliwości zawężenia filtra do tak małej wartości, żeby CW stało się nieczytelne
#24 - odpowiedź "b" jest też bardzo poprawna, przy PSK sygnał zanika do momentu zmiany fazy, a potem narasta (root raised cosine filter) - inaczej powstawałyby okropne wstęgi boczne
#26 - ciężko powiedzieć, strzelam że CW z przeciętnego transceivera przy 30-35WPM zajmie więcej pasma niż PSK31
#31 A + B
#65 - C to bezpośrednia konsekwencja B, a w zasadzie A też się odbywa w takim nieliniowym elemencie
#75 - w powietrzu rozchodzą się fale akutstyczne, trzeba doprecyzować, że chodzi o falę EM
#76 - wszystkie odpowiedzi są poprawne, "Jaki minimalny zakres" ?
#77 - przerywanie fali nośnej to też zmiana amplitudy, do zera, ale jednak zmiana.
#104 - może warto dodać, że chodzi o odbiór SSB/CW?
#109 - jak nisko, to dookoólna... ;-)
#169 - czy gdziekolwiek używa się nazwy "detektor mnożący"? może warto zastąpić to  mieszaczem? albo po prostu zapytać, dlaczego używa się BFO do odbioru CW
#218 - 50dBm - 12dB tłumienia = 38dBm, czyli ~6W, czyli 6%.. a takiej odpowiedzi brak
#275 - trudne pytanie, żadna odpowiedź nie brzmi dobrze, włączając A, dodatkowo w fabrycznych sprzętach chyba bardzo rzadko stosuje się mieszanie kwadraturowe, a częściej samplowanie bezpośrednie. Tak czy siak, odpowiedziałbym "w celu uniknięcia wzajemnego nakładania się sygnałów o częstotliwościach f+x oraz f-x, gdzie f to częstotliwość doprowadzona do portu LO mieszacza"
#304 - na ziemi nie ma szczytów pomiędzy którymi występuje pusta przestrzeń :->
#318 - zmieniłbym 70cm na 6m w odpowiedzi A, 50MHz jest dużo popularniejsze od 430 do MS
#340 - nie zasilanej -> niezasilanej

Czy ktoś chciałby ocenić zasadność w/w zanim zacznę robić PRkę?

**Comment by wprzyb** [comment]
Dzięki za w/w :)

**Comment by canislupus11** [comment]
Uwagi uwzględnione.
