### ISSUE TITLE
Sugestia dotycząca pytania kat. A, dział 1, nr 16

### ISSUE THREAD

**Issue by fethmalcolm** [HackerspaceKRK/pytania-egzaminacyjne#93]
**Aktualna treść pytania:** Wartość skuteczna napięcia sieciowego wynosi 230 V, ile wynosi jego amplituda?

**Odpowiedzi:** 230 V, 324 V, 220 V

---

Treść uwagi: 

230×√2=325,2691193458= ~325V

Pozdro Malcolm

**Comment by canislupus11** [comment]
Oczywiście, racja, już zrobiłem stosowną poprawkę i pullrequesta
